Update README.md
MiyasakaKufu/golang-study pull request #6
Opened 2024-07-29 14:16 UTC by MiyasakaKufu

2024-07-29 14:17 UTC, MiyasakaKufu commented
https://github.com/MiyasakaKufu/golang-study/invitations

2024-07-29 14:18 UTC, Matama091 requested changes
もっと良いコメントを書くように心がけましょう

2024-07-29 14:18 UTC, Matama091 commented on README.md
> +- PR 出すよ〜〜〜ん
[must]ここ修正してください

2024-07-29 14:19 UTC, closed without merging

2024-07-29 14:19 UTC, MiyasakaKufu commented
要件が変更されたため、クローズします。

2024-07-30 10:23 UTC, MiyasakaKufu commented on README.md
> +- PR 出すよ〜〜〜ん
これがあと数ヶ月も続くのか...